spring.datasource.url=jdbc:mysql://localhost:3306/testschema
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.type=trace

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=fitrackerapp@gmail.com
spring.mail.password=unyg opmb lbmx dwgz 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Logging configuration
logging.level.root=INFO
logging.level.com.app.fitrack=DEBUG
logging.level.com.app.fitrack.service.NutritionixService=DEBUG
logging.level.com.app.fitrack.controller.MealController=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=TRACE

# Console output formatting
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# File logging
logging.file.name=logs/fitrack.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Nutritionix API Configuration
nutritionix.api.appId=e9ba5791
nutritionix.api.key=d3b79f81df8614c0249de280c9ce9ff0

app.base-url=http://localhost:8080

# File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true

# Static Resource Configuration
spring.web.resources.static-locations=classpath:/static/,file:uploads/

# Log JDBC Bind Parameters
logging.level.org.hibernate.type.descriptor.sql=trace

# Log SQL Statements
logging.level.org.hibernate.SQL=debug

# Log Spring Transaction Manager activity
logging.level.org.springframework.transaction=trace
logging.level.org.springframework.orm.jpa=trace
logging.level.org.springframework.jdbc.core=trace


cloudinary.cloud_name=dqrdqpgyj
cloudinary.api_key=586623157567884
cloudinary.api_secret=eCLhAH3jchMMumyfgIScbbd-Guo
